[package]
name = "blazelint"
version = "0.1.1"
edition = "2021"
authors = ["Chamal Randika Mallawaarachchi, Rukshan Ranasinghe, Subhoda Pathum"]
description = "A code linter for Ballerina programming language"
license = "MIT"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.10"
