name: Publish crate

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install toml-cli
        run: cargo install toml-cli

      - name: Verify tag matches Cargo.toml version
        if: startsWith(github.ref, 'refs/tags/')
        run: test "v$(toml get Cargo.toml package.version --raw)" = "${{ github.ref_name }}"

      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: BlazeLint ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish
