name: Release SRS PDF

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: latest

      - name: Compile Software Requirements Specification
        run: typst compile docs/SRS.typ docs/software_requirements_analysis.pdf

      - name: Upload SRS PDF to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: docs/software_requirements_analysis.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
