name: Release SRS PDF

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: latest

      - name: Compile Software Requirements Specification
        run: typst compile docs/SRS.typ docs/software_requirements_analysis.pdf

      - name: Upload SRS PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: software-requirements-analysis
          path: docs/software_requirements_analysis.pdf
